[project]
name = "microTPCT"
version = "1.0.0-dev"
description = "Microprotein bioinformatics toolkit"
requires-python = ">=3.12"

authors = [
    {name = "Ambre Bordas", email = "ambre@example.com"},
    {name = "Meredith Biteau", email = "meredith@example.com"},
    {name = "Ambroise Loab", email = "ambroise@example.com"},
    {name = "No√© Cursimaux", email = "noe@example.com"},
    {name = "Basile Bergeron", email = "basile@example.com"}
]

# Find packages in src/
[tool.setuptools.packages.find]
where = ["src"]

# entry point
[project.scripts]
microTPCT = "microtpct.interfaces.cli:cli"
